[package]
name = "autofate"
version = "0.1.0"
authors = ["Chris Miceli <chris@miceli.net.au>"]
edition = "2018"

[dependencies]
git2 = "0.13"
log = "0.4"
simple_logger = "1.9.0"
scopeguard = "1.1.0"
walkdir = "2.3.1"
yaml-rust = "0.4.4"
